
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongoDB
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitMQ
    ports:
      - "5672:5672"   # AMQP protocol
      - "15672:15672" # Management UI
  
  user-service:
    build: ./user-service
    container_name: user_servuce
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  task-service:
    build: ./task-service
    container_name: task_service
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    

volumes:
  mongo_data: